# -*- coding: utf-8 -*-
"""coffe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19eUOJbo9wf9RoI-APIBT-xZRjYbEkxx_
"""

#aqui estao algus produtos que cataloguei no formato de dicionario.
produto = {
    "café da rosa": {
        "preço": 7.0,
        "quantidade": 50,
        "ingredientes": ["café artesanal", "açúcar", "água quente"]
    },
    "cappucino aurora": {
        "preço": 10.0,
        "quantidade": 60,
        "ingredientes": ["café espresso", "leite vaporizado", "chocolate em pó", "canela"]
    },
    "brisa da serra": {
        "preço": 15.0,
        "quantidade": 40,
        "ingredientes": ["chá de frutas vermelhas", "mel", "gelo", "limão"]
    },
    "carinho em xicara": {
        "preço": 12.0,
        "quantidade": 30,
        "ingredientes": ["leite", "baunilha", "chantilly", "essência de lavanda"]
    },
    "cha da tia": {
        "preço": 8.0,
        "quantidade": 20,
        "ingredientes": ["chá preto", "limão", "mel"]
    },
    "bolo da vovo": {
        "preço": 13.0,
        "quantidade": 25,
        "ingredientes": ["farinha de trigo", "ovos", "açúcar", "leite", "fermento", "baunilha"]
    },
    "nuvem de chocolate": {
        "preço": 7.0,
        "quantidade": 45,
        "ingredientes": ["chocolate ao leite", "creme de leite", "açúcar", "cacau"]
    },
    "pão de queijo": {
        "preço": 2.0,
        "quantidade": 30,
        "ingredientes": ["polvilho", "queijo minas", "leite", "ovos", "óleo"]
    },
    "torta da rosa": {
        "preço": 9.0,
        "quantidade": 35,
        "ingredientes": ["massa crocante", "creme de baunilha", "frutas vermelhas"]
    },
    "Empadinha da Casa": {
        "preço": 5.0,
        "quantidade": 29,
        "ingredientes": ['farinha de trigo', 'manteiga', 'frango desfiado', 'creme de leite', 'azeitonas']
    }
}


# esse codigo irá adicionar um produto que desejar.
def adicionar_produto():
    nome_produto = input("Digite o nome do produto: ")
    preco_produto = float(input("Digite o preço do produto: "))
    quantidade_produto = int(input("Digite a quantidade do produto: "))
    nomes_ingredientes = input("Digite os ingredientes do produto (separados por vírgula): ")
    lista_ingredientes = [item.strip() for item in nomes_ingredientes.split(",")]
#esse comando aqui em baixo que vai fica responsvael por guarda o produto.
    produto[nome_produto] = {
        "preço": preco_produto,
        "quantidade": quantidade_produto,
        "ingredientes": lista_ingredientes
    }

    print(f"\nProduto '{nome_produto}' adicionado com sucesso!\n")

# aqui vai aparecer os produtos catalogados.
def listar_produtos():
    print("\n")
    print("╔═════════════════════════════════════╗")
    print("║   🍰   Lista de produto   🍰       ║")
    print("╚═════════════════════════════════════╝")
    print("\n")
    print(f"{'Nome':<25} {'Preço':<10} {'Quantidade'} {'Ingredientes'}")
    print("-" * 70)

    for nome, dados in produto.items():
        ingredientes = ", ".join(dados["ingredientes"])
        print(f"{nome:<25} R${dados['preço']:<10} {dados['quantidade']:<10} {ingredientes}")
    print("\n")

#esse comando aqui em baixo que vai guarda o clientes adicionados.
clientes = {}

# esse codigo ira  adicionar um cliente no sistema.
def adicionar_cliente():
    nome_cliente = input("Digite o nome do cliente: ")
    email_cliente = input("Digite o e-mail do cliente: ")
    telefone_cliente = input("Digite o telefone do cliente: ")
  #esse comando aqui em baixo vai guarda o cliente no sistema.
    clientes[nome_cliente] = {
        "email": email_cliente,
        "telefone": telefone_cliente
    }
#se o clinte for adicionado ira aparecer que o clinte foi adicionado.
    print(f"\nCliente '{nome_cliente}' adicionado com sucesso!\n")

# aqui vai mostrar os clientes.
def listar_clientes():
    if len(clientes) == 0:
        print("\n")
        print("Nenhum cliente cadastrado ainda.")
        print("\n")
        return

    print("\n")
    print("╔═════════════════════════════════════╗")
    print("║     ☕ Lista de Clientes ☕       ║")
    print("╚═════════════════════════════════════╝")
    print("\n")
    print(f"{'Nome':<25} {'E-mail':<30} {'Telefone'}")
    print("-" * 70)

    for nome, dados in clientes.items():
        print(f"{nome:<25} {dados['email']:<30} {dados['telefone']}")
    print("\n")

#essa aqui e a função para realizar pedido.

def realizar_pedido():
    if len(produto) == 0:
        print("Nenhum produto disponível para venda.")
        return
#esse aqui vai tentar encontrar o nome do cliente se ele tiver cadastro.
    nome_cliente = input("Digite o nome do cliente: ")
#caso o cliente nao for cadastrado irá aparece que ele não foi encontrado.
    if nome_cliente not in clientes:
        print("Cliente não encontrado. Cadastre o cliente.")
        return

    pedido = []
    total = 0
#esse aqui e para digitar o nome do protudo da lista de produtos,
    while True:
        listar_produtos()
        nome_produto = input("Digite o nome do produto (ou 'sair' para finalizar): ").lower()
#se digitar sair ira parar.
        if nome_produto == "sair":
            break
#caso nao tenha o produto, ira aparecer que não foi encontrado.
        if nome_produto not in produto:
            print("Produto não foi encontrado. Tente novamente.")
            continue
#esse aqui irá adicionar a quantidade de produto que o clienter quer.
        try:
            quantidade = int(input(f"Digite quantos '{nome_produto}' o cliente quer: "))
        except ValueError:
            print("Quantidade inválida. Digite um número.") #caso não tenha a quantidade, ira aparece quantidade invalida.
            continue

        if quantidade > produto[nome_produto]["quantidade"]:
            print("Quantidade indisponível no estoque.")
            continue

        #esse aqui vai fica responsavel por atualizar o estoque.
        produto[nome_produto]["quantidade"] -= quantidade

        # esse aqui vai fica responsavel por calcular o total do pedido.
        subtotal = produto[nome_produto]["preço"] * quantidade
        total += subtotal

        pedido.append((nome_produto, quantidade, subtotal))
        print(f"Adicionado: {quantidade}x {nome_produto} - R${subtotal:.2f}")


    if pedido:
        print("\nResumo do pedido:")
        for item in pedido:
            print(f"{item[1]}x {item[0]} - R${item[2]:.2f}") #esse e apenas um resumo do pedido, que ira aparecer o total do pedido e os pedidos feitos, e se nenhum pedido foi feito.
        print(f"Total do pedido: R${total:.2f}")
    else:
        print("Nenhum item foi adicionado ao pedido.")


# esse aqui e um menu interativo simples, para poderem escolher qual sistema quer acessar.
def exibir_menu():
    print("╔════════════════════════════════════════════════╗")
    print("║   🍰 Bem-vindo ao Coffee Shops Tia Rosa! 🍰   ║")
    print("╚════════════════════════════════════════════════╝")
    print("\n")
    print("1 - Adicionar Produto")
    print("2 - Listar Produtos")
    print("3 - Adicionar Cliente")
    print("4 - Listar Clientes")
    print("5 - realizar pedido")
    print("0 - Sair")
    escolha = input("\nEscolha uma opção: ")

    if escolha == "1":
        adicionar_produto()
    elif escolha == "2":
        listar_produtos()
    elif escolha == "3":
        adicionar_cliente()
    elif escolha == "4":
        listar_clientes()
    elif escolha =="5":
         realizar_pedido()
    elif escolha == "0":
        print(" Você escolheu sair. Até logo!")
        exit()
    else:
        print("Opção inválida. Tente novamente.")


while True:
    exibir_menu()